/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellSettingsRouteImport } from './routes/_shell/settings'
import { Route as ShellProjectRouteImport } from './routes/_shell/project'
import { Route as ShellInboxRouteImport } from './routes/_shell/inbox'
import { Route as ShellGraphRouteImport } from './routes/_shell/graph'
import { Route as ShellDocumentsIndexRouteImport } from './routes/_shell/documents/index'
import { Route as ShellDocumentsDocumentIdRouteImport } from './routes/_shell/documents/$documentId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProjectRoute = ShellProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => ShellRoute,
} as any)
const ShellInboxRoute = ShellInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => ShellRoute,
} as any)
const ShellGraphRoute = ShellGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDocumentsIndexRoute = ShellDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDocumentsDocumentIdRoute =
  ShellDocumentsDocumentIdRouteImport.update({
    id: '/documents/$documentId',
    path: '/documents/$documentId',
    getParentRoute: () => ShellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/login': typeof LoginRoute
  '/graph': typeof ShellGraphRoute
  '/inbox': typeof ShellInboxRoute
  '/project': typeof ShellProjectRoute
  '/settings': typeof ShellSettingsRoute
  '/documents/$documentId': typeof ShellDocumentsDocumentIdRoute
  '/documents/': typeof ShellDocumentsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/graph': typeof ShellGraphRoute
  '/inbox': typeof ShellInboxRoute
  '/project': typeof ShellProjectRoute
  '/settings': typeof ShellSettingsRoute
  '/': typeof ShellIndexRoute
  '/documents/$documentId': typeof ShellDocumentsDocumentIdRoute
  '/documents': typeof ShellDocumentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/_shell/graph': typeof ShellGraphRoute
  '/_shell/inbox': typeof ShellInboxRoute
  '/_shell/project': typeof ShellProjectRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/documents/$documentId': typeof ShellDocumentsDocumentIdRoute
  '/_shell/documents/': typeof ShellDocumentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/graph'
    | '/inbox'
    | '/project'
    | '/settings'
    | '/documents/$documentId'
    | '/documents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/graph'
    | '/inbox'
    | '/project'
    | '/settings'
    | '/'
    | '/documents/$documentId'
    | '/documents'
  id:
    | '__root__'
    | '/_shell'
    | '/login'
    | '/_shell/graph'
    | '/_shell/inbox'
    | '/_shell/project'
    | '/_shell/settings'
    | '/_shell/'
    | '/_shell/documents/$documentId'
    | '/_shell/documents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/project': {
      id: '/_shell/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ShellProjectRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/inbox': {
      id: '/_shell/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof ShellInboxRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/graph': {
      id: '/_shell/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof ShellGraphRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/documents/': {
      id: '/_shell/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof ShellDocumentsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/documents/$documentId': {
      id: '/_shell/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof ShellDocumentsDocumentIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellGraphRoute: typeof ShellGraphRoute
  ShellInboxRoute: typeof ShellInboxRoute
  ShellProjectRoute: typeof ShellProjectRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellDocumentsDocumentIdRoute: typeof ShellDocumentsDocumentIdRoute
  ShellDocumentsIndexRoute: typeof ShellDocumentsIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellGraphRoute: ShellGraphRoute,
  ShellInboxRoute: ShellInboxRoute,
  ShellProjectRoute: ShellProjectRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellDocumentsDocumentIdRoute: ShellDocumentsDocumentIdRoute,
  ShellDocumentsIndexRoute: ShellDocumentsIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
