import { describe, expect, it } from 'bun:test';
import { readdir, readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { z } from 'zod';
import { CONTRACTS } from '../../tools/contracts';
import {
  buildContracts,
  contractComment,
} from '../../tools/generate-contracts';

const appRoot = fileURLToPath(new URL('../../src/app/', import.meta.url));
const files = buildContracts('1.2.3');
const names = Object.keys(CONTRACTS);

function schemaOf(name: string): Record<string, unknown> {
  return files.get(`${name}.schema.json`) as Record<string, unknown>;
}

describe('the generated JSON Schema contracts', () => {
  it('holds a schema per contract and an example where one is given', () => {
    const expected = Object.entries(CONTRACTS).flatMap(([name, contract]) =>
      'example' in contract
        ? [`${name}.schema.json`, `${name}.example.json`]
        : [`${name}.schema.json`],
    );
    expect([...files.keys()].sort()).toEqual(expected.sort());
  });

  it('names the service version each schema was generated by', () => {
    for (const name of names) {
      expect(schemaOf(name).$comment).toBe(contractComment('1.2.3'));
      expect(schemaOf(name).type).toBe('object');
    }
  });

  it('states each schema whole: nothing points outside the file', () => {
    for (const name of names) {
      const refs = [
        ...JSON.stringify(schemaOf(name)).matchAll(/"\$ref":"([^"]+)"/g),
      ].map((m) => m[1] ?? '');
      expect(refs.filter((ref) => !ref.startsWith('#'))).toEqual([]);
    }
  });

  it('shows a codec as the string an agent writes, not the value object', () => {
    const { properties } = schemaOf('document') as {
      properties: { document_id: Record<string, unknown> };
    };
    expect(properties.document_id).toMatchObject({
      type: 'string',
      pattern: '^[a-z0-9]+(?:-[a-z0-9]+)*$',
    });
  });

  it('keeps the descriptions an agent reads', () => {
    const { properties } = schemaOf('create-change') as {
      properties: { name: { description?: string } };
    };
    expect(properties.name.description).toBeTruthy();
  });

  it('ships examples that fit the schema beside them', () => {
    for (const name of names) {
      const example = files.get(`${name}.example.json`);
      if (example === undefined) continue;
      const schema = z.fromJSONSchema(
        schemaOf(name) as Parameters<typeof z.fromJSONSchema>[0],
      );
      expect(schema.safeParse(example).success).toBe(true);
    }
  });

  // JSON Schema has no word for a refinement or a transform, so one written
  // at the source would be dropped from the contract without a sound.
  it('finds no rule under src/app/ that JSON Schema cannot state', async () => {
    const sources = (await readdir(appRoot, { recursive: true })).filter(
      (file) => file.endsWith('.ts'),
    );
    for (const file of sources) {
      const source = await readFile(join(appRoot, file), 'utf8');
      if (!source.includes("from 'zod'")) continue;
      expect(source).not.toMatch(/\.(refine|superRefine|transform|check)\(/);
    }
  });
});
