/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.itlibrium.discounts;

import com.itlibrium.discounts.calculation.DiscountCalculation;
import com.itlibrium.discounts.calculation.DiscountPolicyFactory;
import com.itlibrium.discounts.calculation.DiscountsConfigProvider;
import com.itlibrium.discounts.offers.Offer;
import com.itlibrium.discounts.offers.Product;
import com.itlibrium.discounts.users.UserId;
import com.itlibrium.discounts.users.UserStatusProvider;
import com.itlibrium.discounts.weather.openmeteo.OpenMeteoWeatherProvider;
import io.vavr.collection.List;

import java.util.UUID;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        DiscountCalculation discountCalculation = new DiscountCalculation(
            new DiscountPolicyFactory(
                new DiscountsConfigProvider(), new UserStatusProvider(), new OpenMeteoWeatherProvider()
            )
        );
        discountCalculation.calculate(new Offer(List.of(new Product())), new UserId(UUID.randomUUID()));
    }
}



